# Login
POST http://localhost:5050/auth/login
Content-Type: application/json

{
    "username": "",
    "password": ""
}

# Register
###
POST http://localhost:5050/auth/register
Content-Type: application/json

{
    "username": "",
    "email" : "",
    "password": "",
    "admin": true
}

# GET all users
###
GET http://localhost:5050/v1/users
Authorization: Beaer 

### DELETE a user
DELETE http://localhost:5050/v1/users/64021691e61bd5ddf66e0447
Authorization: Beaer 


# REFRESH TOKEN
###
POST http://localhost:5050/auth/token 

# LOGOUT
###
POST http://localhost:5050/auth/logout
